# Generated by Django 5.2.4 on 2026-08-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id_area', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('responsable', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=45, null=True)),
                ('correlativo', models.IntegerField(blank=True, null=True)),
                ('activo', models.IntegerField()),
            ],
            options={
                'db_table': 'areas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id_banco', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=2, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('activo', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'bancos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('nombre_ingles', models.CharField(blank=True, max_length=100, null=True)),
                ('nivel', models.IntegerField(blank=True, null=True)),
                ('activo', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'cargos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioModulo',
            fields=[
                ('id_usuario_modulo', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'usuario_modulo',
                'managed': False,
            },
        ),
    ]
