# Generated by Django 5.2.4 on 2026-08-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('iniciales', models.CharField(blank=True, max_length=45, null=True)),
                ('ruc', models.CharField(blank=True, max_length=45, null=True)),
                ('direccion', models.CharField(max_length=600)),
                ('tipo', models.IntegerField(blank=True, null=True)),
                ('forma_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_ingreso', models.DateTimeField(blank=True, null=True)),
                ('pagina_web', models.CharField(blank=True, max_length=100, null=True)),
                ('representante_legal', models.CharField(blank=True, max_length=100, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.CharField(default='1', max_length=1)),
            ],
            options={
                'db_table': 'clientes',
                'ordering': ['nombre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('activo', models.IntegerField(default=1)),
                ('cotizaciones', models.IntegerField(default=0)),
                ('orden_compra', models.IntegerField(default=0)),
                ('facturacion', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'estados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id_modulo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('activo', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'modulos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id_nota', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=2, unique=True)),
                ('descripcion', models.TextField()),
                ('activo', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'notas',
                'ordering': ['codigo'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObjetivoAnual',
            fields=[
                ('id_objetivo', models.AutoField(primary_key=True, serialize=False)),
                ('anno', models.PositiveIntegerField(db_column='anno')),
                ('minimo', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('maximo', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('activo', models.BooleanField(blank=True, default=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'objetivo_anual',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObjetivoAnualArea',
            fields=[
                ('id_objetivo_anno', models.AutoField(primary_key=True, serialize=False)),
                ('minimo', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('maximo', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'objetivo_anual_area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=30)),
                ('codigo2', models.CharField(blank=True, max_length=60, null=True)),
                ('nombre', models.TextField()),
                ('contenido_valor', models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=10, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_soles', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('precio_dolares', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('cantidad', models.IntegerField(blank=True, default=0, null=True)),
                ('stock_min', models.IntegerField(blank=True, default=0, null=True)),
                ('stock_max', models.IntegerField(blank=True, default=0, null=True)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'producto',
                'ordering': ['nombre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id_representante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_representante', models.CharField(max_length=100)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('movil', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'representantes',
                'ordering': ['nombre_representante'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id_rubro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('activo', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'rubro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCotizacion',
            fields=[
                ('id_tipo', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('activo', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'tipo_coti',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoGasto',
            fields=[
                ('id_tipo_gasto', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=2)),
                ('nombre', models.CharField(max_length=1000)),
                ('activo', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Gasto',
                'verbose_name_plural': 'Tipos de Gasto',
                'db_table': 'tipo_gasto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoGastoDetalle',
            fields=[
                ('id_gasto_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=1000)),
                ('activo', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'tipo_gasto_detalle',
                'ordering': ['nombre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoMarca',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('activo', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'tipo_marca',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPersonal',
            fields=[
                ('id_personal', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=45)),
                ('nombre', models.CharField(max_length=1000)),
                ('costo_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('costo_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('activo', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'tipo_personal',
                'ordering': ['nombre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id_medida', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'db_table': 'unidad_medida',
                'ordering': ['nombre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnidadTiempo',
            fields=[
                ('id_tiempo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=2)),
                ('nombre', models.CharField(max_length=50)),
                ('activo', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Unidad de Tiempo',
                'verbose_name_plural': 'Unidades de Tiempo',
                'db_table': 'unidad_tiempo',
                'managed': False,
            },
        ),
    ]
