# Generated by Django 5.2.4 on 2026-07-10 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('urgente', 'Urgente'), ('atencion', 'Atención'), ('informativo', 'Informativo')], max_length=20)),
                ('modulo', models.CharField(choices=[('comercial', 'Comercial'), ('logistica', 'Logística')], max_length=20)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('leido', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.IntegerField(default=0)),
                ('referencia_id', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notificaciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
