# Generated by Django 5.2.4 on 2026-07-31 15:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SegUsuario',
            fields=[
                ('usuario_usu', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('password_usu', models.CharField(max_length=255)),
                ('nomb_cort_usu', models.CharField(blank=True, max_length=150, null=True)),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('ape', models.CharField(blank=True, max_length=50, null=True)),
                ('area', models.IntegerField(blank=True, null=True)),
                ('cargo', models.CharField(blank=True, max_length=5, null=True)),
                ('ban', models.CharField(blank=True, max_length=5, null=True)),
                ('banc', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'seg_usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VcTabAreas',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('responsable', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('correlativo', models.IntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('std', models.IntegerField(blank=True, null=True)),
                ('org', models.CharField(blank=True, max_length=150, null=True)),
                ('nomp', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'vc_tab_areas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VcTabBancos',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'vc_tab_bancos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VcTabCargos',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('nom', models.CharField(blank=True, max_length=150, null=True)),
                ('niv', models.PositiveIntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'vc_tab_cargos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CajaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('monto_base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_gastado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_sobrante', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cerrada', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GuiaSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('origen', models.CharField(max_length=150)),
                ('destino', models.CharField(max_length=150)),
                ('responsable', models.CharField(max_length=120)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Enviada', 'Enviada'), ('Recibida', 'Recibida')], default='Pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='RazonSocial',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ruc', models.CharField(max_length=11, unique=True)),
                ('razon_social', models.CharField(max_length=255)),
                ('estado', models.CharField(default='inicial', max_length=50)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'caja_chica_api_razonsocial',
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Ingreso', 'Ingreso'), ('Egreso', 'Egreso'), ('Aprobación', 'Aprobación'), ('Eliminación', 'Eliminación'), ('Actualización', 'Actualización')], max_length=50)),
                ('accion', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArqueoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_operacion', models.CharField(db_index=True, max_length=50, unique=True)),
                ('fecha', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('entradas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_final', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observaciones', models.TextField(blank=True)),
                ('cerrada', models.BooleanField(db_index=True, default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arqueos_caja', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArqueoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='arqueos/')),
                ('tipo', models.CharField(choices=[('comprobante', 'Comprobante'), ('foto', 'Foto'), ('otro', 'Otro')], default='comprobante', max_length=20)),
                ('arqueo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='caja_chica_api.arqueocaja')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_operacion', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Número de Operación')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('tipo_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('ruc', models.CharField(blank=True, max_length=20, null=True)),
                ('razon_social', models.CharField(blank=True, max_length=255, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_documentado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total acumulado de todos los documentos de la liquidación', max_digits=12)),
                ('nombre_archivo', models.CharField(blank=True, max_length=255, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('archivo_url', models.URLField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_subidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CorreccionOCR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=100)),
                ('valor_original', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_correccion', models.CharField(max_length=255)),
                ('fecha_correccion', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correcciones', to='caja_chica_api.documentogasto')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada')], db_index=True, default='Cerrada', max_length=10)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estados_caja', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GuiaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='caja_chica_api.guiasalida')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalArqueoCaja',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numero_operacion', models.CharField(db_index=True, max_length=50)),
                ('fecha', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('entradas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_final', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observaciones', models.TextField(blank=True)),
                ('cerrada', models.BooleanField(db_index=True, default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical arqueo caja',
                'verbose_name_plural': 'historical arqueo cajas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('total_soles', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_dolares', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('estado', models.CharField(choices=[('Pendiente de Envío', 'Pendiente de Envío'), ('Pendiente para Atención', 'Pendiente para Atención'), ('Atendido, Pendiente de Liquidación', 'Atendido, Pendiente de Liquidación'), ('Liquidación enviada para Aprobación', 'Liquidación enviada para Aprobación'), ('Liquidación Aprobada', 'Liquidación Aprobada'), ('Rechazado', 'Rechazado')], db_index=True, default='Pendiente de Envío', max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='documentogasto',
            name='liquidacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='caja_chica_api.liquidacion'),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('leido', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OperacionSecuencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('secuencia', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('tipo', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_solicitud', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('fecha', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('hora', models.TimeField(db_index=True, default=django.utils.timezone.now)),
                ('tipo_solicitud', models.CharField(choices=[('Viáticos', 'Viáticos'), ('Movilidad', 'Movilidad'), ('Compras', 'Compras'), ('Otros Gastos', 'Otros Gastos')], default='Compras', max_length=50)),
                ('concepto_gasto', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('Pendiente de Envío', 'Pendiente de Envío'), ('Pendiente para Atención', 'Pendiente para Atención'), ('Atendido, Pendiente de Liquidación', 'Atendido, Pendiente de Liquidación'), ('Liquidación enviada para Aprobación', 'Liquidación enviada para Aprobación'), ('Liquidación Aprobada', 'Liquidación Aprobada'), ('Rechazado', 'Rechazado')], db_index=True, default='Pendiente de Envío', max_length=80)),
                ('area', models.CharField(max_length=100)),
                ('total_soles', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_dolares', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('banco', models.CharField(blank=True, max_length=50)),
                ('numero_cuenta', models.CharField(blank=True, max_length=50)),
                ('fecha_transferencia', models.DateField(blank=True, db_index=True, null=True)),
                ('fecha_liquidacion', models.DateField(blank=True, db_index=True, null=True)),
                ('observacion', models.TextField(blank=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('destinatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_recibidas', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Gasto',
                'verbose_name_plural': 'Solicitudes de Gasto',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones', to='caja_chica_api.solicitud'),
        ),
        migrations.CreateModel(
            name='HistoricalLiquidacion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('total_soles', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_dolares', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('estado', models.CharField(choices=[('Pendiente de Envío', 'Pendiente de Envío'), ('Pendiente para Atención', 'Pendiente para Atención'), ('Atendido, Pendiente de Liquidación', 'Atendido, Pendiente de Liquidación'), ('Liquidación enviada para Aprobación', 'Liquidación enviada para Aprobación'), ('Liquidación Aprobada', 'Liquidación Aprobada'), ('Rechazado', 'Rechazado')], db_index=True, default='Pendiente de Envío', max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='caja_chica_api.solicitud')),
            ],
            options={
                'verbose_name': 'historical liquidacion',
                'verbose_name_plural': 'historical liquidacions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='documentogasto',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='caja_chica_api.solicitud'),
        ),
        migrations.CreateModel(
            name='SolicitudArqueo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_operacion', models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='N° Operación')),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Solicitud')),
                ('monto_arqueo', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto del Arqueo')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('incluida_en_arqueo', 'Incluida en Arqueo'), ('liquidada', 'Liquidada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_arqueo', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Solicitud de Arqueo',
                'verbose_name_plural': 'Solicitudes de Arqueo',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='ArqueoMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10)),
                ('descripcion', models.CharField(max_length=255)),
                ('entradas', models.DecimalField(decimal_places=2, max_digits=12)),
                ('origen', models.CharField(choices=[('manual', 'Manual'), ('solicitud', 'Solicitud')], default='manual', max_length=10)),
                ('arqueo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='caja_chica_api.arqueocaja')),
                ('solicitud_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caja_chica_api.solicitudarqueo')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudGastoEstadoHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(choices=[('Pendiente de Envío', 'Pendiente de Envío'), ('Pendiente para Atención', 'Pendiente para Atención'), ('Atendido, Pendiente de Liquidación', 'Atendido, Pendiente de Liquidación'), ('Liquidación enviada para Aprobación', 'Liquidación enviada para Aprobación'), ('Liquidación Aprobada', 'Liquidación Aprobada'), ('Rechazado', 'Rechazado')], max_length=80)),
                ('estado_nuevo', models.CharField(choices=[('Pendiente de Envío', 'Pendiente de Envío'), ('Pendiente para Atención', 'Pendiente para Atención'), ('Atendido, Pendiente de Liquidación', 'Atendido, Pendiente de Liquidación'), ('Liquidación enviada para Aprobación', 'Liquidación enviada para Aprobación'), ('Liquidación Aprobada', 'Liquidación Aprobada'), ('Rechazado', 'Rechazado')], max_length=80)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='caja_chica_api.solicitud')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='liquidacion',
            index=models.Index(fields=['fecha'], name='caja_chica__fecha_7169ba_idx'),
        ),
        migrations.AddIndex(
            model_name='liquidacion',
            index=models.Index(fields=['usuario'], name='caja_chica__usuario_075973_idx'),
        ),
        migrations.AddIndex(
            model_name='liquidacion',
            index=models.Index(fields=['estado'], name='caja_chica__estado_45d579_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudarqueo',
            index=models.Index(fields=['numero_operacion'], name='caja_chica__numero__3d5d4a_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudarqueo',
            index=models.Index(fields=['estado'], name='caja_chica__estado_c6d48d_idx'),
        ),
    ]
