# Generated by Django 5.2.4 on 2026-08-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja_chica_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCajaChica',
            fields=[
                ('id_caja_chica', models.AutoField(primary_key=True, serialize=False)),
                ('id_registro', models.IntegerField()),
                ('nivel_grupo', models.IntegerField(blank=True, null=True)),
                ('cog', models.CharField(blank=True, max_length=100, null=True)),
                ('num', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('banco', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_cuenta', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_moneda', models.CharField(blank=True, max_length=45, null=True)),
                ('monto_soles', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('tipo_cambio', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10, null=True)),
                ('monto_dolares', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('concepto', models.CharField(blank=True, max_length=1000, null=True)),
                ('fecha_transferencia', models.DateTimeField(blank=True, null=True)),
                ('fecha_liquidacion', models.DateTimeField(blank=True, null=True)),
                ('observacion', models.CharField(blank=True, max_length=500, null=True)),
                ('luo', models.CharField(blank=True, max_length=255, null=True)),
                ('lud', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('tipo_movimiento', models.CharField(blank=True, max_length=45, null=True)),
                ('tipo_gasto', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'solicitud_caja_chica',
                'managed': False,
            },
        ),
    ]
