# Generated by Django 5.2.4 on 2026-08-13 19:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlmacenNew',
            fields=[
                ('idalmacen', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('usuario_id_usuario', models.IntegerField()),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'almacen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClienteLogistica',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('ruc', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CostoAlmacen',
            fields=[
                ('idcosto_almacen', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=100)),
                ('activo', models.CharField(default='1', max_length=45)),
            ],
            options={
                'db_table': 'costo_almacen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DashboardCotizacion',
            fields=[
                ('numero', models.CharField(blank=True, db_column='cotin', max_length=70, null=True)),
                ('fecha', models.DateField(db_column='cotif', db_index=True, default=django.utils.timezone.now)),
                ('referencia', models.CharField(blank=True, db_column='refer', max_length=150, null=True)),
                ('num_reg', models.AutoField(db_column='num_reg', primary_key=True, serialize=False)),
                ('cliente_codigo', models.CharField(blank=True, db_column='empre', max_length=5, null=True)),
                ('nombr', models.CharField(blank=True, db_column='nombr', max_length=70, null=True)),
                ('cargr', models.CharField(blank=True, db_column='cargr', max_length=70, null=True)),
                ('codir', models.CharField(blank=True, db_column='codir', max_length=5, null=True)),
                ('teler', models.CharField(blank=True, db_column='teler', max_length=50, null=True)),
                ('movir', models.CharField(blank=True, db_column='movir', max_length=50, null=True)),
                ('mailr', models.CharField(blank=True, db_column='mailr', max_length=50, null=True)),
                ('prob', models.CharField(blank=True, db_column='prob', max_length=1, null=True)),
                ('cotit', models.CharField(blank=True, db_column='cotit', max_length=1, null=True)),
                ('area_codigo', models.CharField(blank=True, db_column='area', max_length=1, null=True)),
                ('estado_codigo', models.CharField(blank=True, db_column='estad', max_length=1, null=True)),
                ('envio', models.IntegerField(blank=True, db_column='envio', null=True)),
                ('tot_c', models.DecimalField(blank=True, db_column='tot_c', decimal_places=2, max_digits=12, null=True)),
                ('fpago', models.CharField(blank=True, db_column='fpago', max_length=50, null=True)),
                ('lugar', models.CharField(blank=True, db_column='lugar', max_length=100, null=True)),
                ('entrp', models.IntegerField(blank=True, db_column='entrp', null=True)),
                ('entrf', models.CharField(blank=True, db_column='entrf', max_length=50, null=True)),
                ('tmone', models.CharField(blank=True, db_column='tmone', max_length=20, null=True)),
                ('tcamb', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('igv', models.CharField(blank=True, db_column='igv', max_length=1, null=True)),
                ('plazo', models.IntegerField(blank=True, db_column='plazo', null=True)),
                ('tot_d', models.CharField(blank=True, db_column='tot_d', max_length=1, null=True)),
                ('por_c', models.IntegerField(blank=True, db_column='por_c', null=True)),
                ('tot_s', models.CharField(blank=True, db_column='tot_s', max_length=1, null=True)),
                ('valid', models.IntegerField(blank=True, db_column='valid', null=True)),
                ('acu_s', models.CharField(blank=True, db_column='acu_s', max_length=1, null=True)),
                ('nombc', models.CharField(blank=True, db_column='nombc', max_length=150, null=True)),
                ('telec', models.CharField(blank=True, db_column='telec', max_length=20, null=True)),
                ('mov1c', models.CharField(blank=True, db_column='mov1c', max_length=20, null=True)),
                ('mov2c', models.CharField(blank=True, db_column='mov2c', max_length=20, null=True)),
                ('mov3c', models.CharField(blank=True, db_column='mov3c', max_length=20, null=True)),
                ('mailc', models.CharField(blank=True, db_column='mailc', max_length=100, null=True)),
                ('nombt', models.CharField(blank=True, db_column='nombt', max_length=150, null=True)),
                ('telet', models.CharField(blank=True, db_column='telet', max_length=20, null=True)),
                ('mov1t', models.CharField(blank=True, db_column='mov1t', max_length=20, null=True)),
                ('mov2t', models.CharField(blank=True, db_column='mov2t', max_length=20, null=True)),
                ('mov3t', models.CharField(blank=True, db_column='mov3t', max_length=20, null=True)),
                ('mailt', models.CharField(blank=True, db_column='mailt', max_length=100, null=True)),
                ('acu_e', models.TextField(blank=True, null=True)),
                ('sald', models.DecimalField(blank=True, db_column='sald', decimal_places=2, max_digits=11, null=True)),
                ('anno', models.CharField(blank=True, db_column='anno', max_length=4, null=True)),
                ('mes', models.CharField(blank=True, db_column='mes', max_length=2, null=True)),
                ('regus', models.CharField(blank=True, db_column='regus', max_length=200, null=True)),
                ('des_a', models.CharField(blank=True, db_column='des_a', max_length=1, null=True)),
                ('des_t', models.CharField(blank=True, db_column='des_t', max_length=1, null=True)),
                ('des_m', models.DecimalField(blank=True, db_column='des_m', decimal_places=2, max_digits=11, null=True)),
                ('des_p', models.DecimalField(blank=True, db_column='des_p', decimal_places=2, max_digits=11, null=True)),
            ],
            options={
                'verbose_name': 'Cotización Dashboard',
                'verbose_name_plural': 'Cotizaciones Dashboard',
                'db_table': 'vc_mov_cotizaciones',
                'ordering': ['-fecha', '-numero'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentoAlmacen',
            fields=[
                ('iddocumento_almacen', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
                ('activo', models.CharField(default='1', max_length=45)),
            ],
            options={
                'db_table': 'documento_almacen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('idgrupo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('activo', models.CharField(default='1', max_length=45)),
            ],
            options={
                'db_table': 'grupo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='vc_tab_clientes_d',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('representante', models.CharField(blank=True, max_length=150, null=True)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('movil', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('empresa', models.CharField(blank=True, max_length=150, null=True)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'vc_tab_clientes_d',
                'ordering': ['representante'],
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Cotizacion',
        ),
        migrations.DeleteModel(
            name='Representante',
        ),
        migrations.DeleteModel(
            name='VcTabBancos',
        ),
        migrations.AlterModelTable(
            name='logisticadashboard',
            table='movimiento',
        ),
        migrations.AlterModelTable(
            name='logisticadashboarddetalle',
            table='movimiento_detalle',
        ),
    ]
