# Generated by Django 5.2.4 on 2026-08-13 19:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CotizacionApertura',
            fields=[
                ('id_apertura', models.AutoField(db_column='id_apertura', primary_key=True, serialize=False)),
                ('anno', models.IntegerField(blank=True, db_column='anno', null=True)),
                ('mes', models.IntegerField(blank=True, db_column='mes', null=True)),
                ('numero_orden', models.CharField(blank=True, db_column='numero_orden', max_length=70, null=True)),
                ('estado_orden', models.IntegerField(blank=True, db_column='estado_orden', default=1, null=True)),
                ('fecha_orden', models.DateTimeField(blank=True, db_column='fecha_orden', null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, db_column='fecha_entrega', null=True)),
                ('mes_entrega', models.IntegerField(blank=True, db_column='mes_entrega', null=True)),
                ('fecha_factura', models.DateTimeField(blank=True, db_column='fecha_factura', null=True)),
                ('orden_plazo_valor', models.IntegerField(blank=True, db_column='orden_plazo_valor', null=True)),
                ('total_orden', models.DecimalField(blank=True, db_column='total_orden', decimal_places=2, max_digits=11, null=True)),
                ('presupuesto', models.DecimalField(blank=True, db_column='presupuesto', decimal_places=2, max_digits=11, null=True)),
                ('orden_compra_equipos', models.DecimalField(blank=True, db_column='orden_compra_equipos', decimal_places=2, max_digits=11, null=True)),
                ('orden_compra_materiales', models.DecimalField(blank=True, db_column='orden_compra_materiales', decimal_places=2, max_digits=11, null=True)),
                ('orden_compra_hh', models.DecimalField(blank=True, db_column='orden_compra_hh', decimal_places=2, max_digits=11, null=True)),
                ('orden_compra_entrega', models.DecimalField(blank=True, db_column='orden_compra_entrega', decimal_places=2, max_digits=11, null=True)),
                ('orden_compra_costo_servicios', models.DecimalField(blank=True, db_column='orden_compra_costo_servicios', decimal_places=2, max_digits=11, null=True)),
                ('orden_compra_otros', models.DecimalField(blank=True, db_column='orden_compra_otros', decimal_places=2, max_digits=11, null=True)),
                ('totfa', models.DecimalField(blank=True, db_column='totfa', decimal_places=2, max_digits=11, null=True)),
                ('salfa', models.DecimalField(blank=True, db_column='salfa', decimal_places=2, max_digits=11, null=True)),
                ('uti_des', models.DecimalField(blank=True, db_column='uti_des', decimal_places=2, max_digits=11, null=True)),
                ('orden_adjunta', models.CharField(blank=True, db_column='orden_adjunta', max_length=255, null=True)),
                ('responsables', models.TextField(blank=True, db_column='responsables', null=True)),
                ('oobs', models.CharField(blank=True, db_column='oobs', max_length=255, null=True)),
                ('doc', models.CharField(blank=True, db_column='doc', max_length=50, null=True)),
                ('do1', models.CharField(blank=True, db_column='do1', max_length=255, null=True)),
                ('do2', models.CharField(blank=True, db_column='do2', max_length=255, null=True)),
                ('do3', models.CharField(blank=True, db_column='do3', max_length=255, null=True)),
                ('ti1', models.CharField(blank=True, db_column='ti1', max_length=255, null=True)),
                ('ti2', models.CharField(blank=True, db_column='ti2', max_length=255, null=True)),
                ('ti3', models.CharField(blank=True, db_column='ti3', max_length=255, null=True)),
                ('des_a', models.CharField(blank=True, db_column='des_a', max_length=1, null=True)),
                ('des_t', models.CharField(blank=True, db_column='des_t', max_length=1, null=True)),
                ('des_m', models.DecimalField(blank=True, db_column='des_m', decimal_places=2, max_digits=11, null=True)),
                ('des_p', models.DecimalField(blank=True, db_column='des_p', decimal_places=2, max_digits=11, null=True)),
                ('anno_a', models.CharField(blank=True, db_column='anno_a', default='2026', max_length=4, null=True)),
                ('prio', models.CharField(blank=True, db_column='prio', default='0', max_length=1, null=True)),
                ('poceq', models.IntegerField(blank=True, db_column='poceq', default=1, null=True)),
                ('pocma', models.IntegerField(blank=True, db_column='pocma', default=1, null=True)),
                ('pocrh', models.IntegerField(blank=True, db_column='pocrh', default=0, null=True)),
                ('pocse', models.IntegerField(blank=True, db_column='pocse', default=0, null=True)),
                ('pocot', models.IntegerField(blank=True, db_column='pocot', default=0, null=True)),
                ('pger', models.IntegerField(blank=True, db_column='pger', default=1, null=True)),
                ('envio', models.IntegerField(blank=True, db_column='envio', null=True)),
                ('pres', models.IntegerField(blank=True, db_column='pres', default=0, null=True)),
            ],
            options={
                'db_table': 'cotizaciones_apertura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CotizacionCondicionGeneral',
            fields=[
                ('id_condicion_general', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, db_column='descripcion', null=True)),
                ('fecha', models.DateTimeField(auto_now=True, db_column='fecha')),
            ],
            options={
                'db_table': 'cotizaciones_condiciones_generales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CotizacionMensaje',
            fields=[
                ('id_mensaje', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('alerta', models.CharField(default='0', max_length=1)),
                ('alerta_fecha', models.DateTimeField(blank=True, null=True)),
                ('alerta_completada', models.DateTimeField(blank=True, null=True)),
                ('completo', models.CharField(default='0', max_length=1)),
                ('activo', models.CharField(default='1', max_length=1)),
            ],
            options={
                'db_table': 'cotizaciones_mensajes',
                'ordering': ['-fecha'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CotizacionSeguimiento',
            fields=[
                ('id_seguimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('detalle', models.CharField(blank=True, max_length=500, null=True)),
                ('activo', models.CharField(default='1', max_length=1)),
            ],
            options={
                'db_table': 'cotizaciones_seguimiento',
                'ordering': ['-fecha'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CotizacionServicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_servicio', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_servicio', models.CharField(blank=True, max_length=100, null=True)),
                ('nivel', models.IntegerField(blank=True, null=True)),
                ('orden', models.IntegerField(blank=True, default=0, null=True)),
                ('codigo_item', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion_item', models.CharField(blank=True, max_length=255, null=True)),
                ('horas', models.IntegerField(blank=True, null=True)),
                ('cantidad_hombres', models.IntegerField(blank=True, null=True)),
                ('costo_hombre_dia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad_dias', models.IntegerField(blank=True, null=True)),
                ('costo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('utilidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cotizado_hombre_dia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cotizado_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descripcion_servicio', models.TextField(blank=True, db_column='descripcion_servicio', null=True)),
            ],
            options={
                'db_table': 'cotizaciones_servicios',
                'ordering': ['orden', 'id_servicio'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CotizacionSuministro',
            fields=[
                ('id_suministro', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_grupo', models.IntegerField()),
                ('nombre_grupo', models.CharField(blank=True, max_length=500, null=True)),
                ('nivel', models.IntegerField(blank=True, null=True)),
                ('orden', models.IntegerField(blank=True, default=0, null=True)),
                ('codigo_item', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=5000)),
                ('observacion', models.CharField(blank=True, max_length=3000, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_unidad', models.CharField(blank=True, max_length=45, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('tiempo_entrega', models.IntegerField(blank=True, null=True)),
                ('costo_precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('costo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('costo_envio_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('costo_envio_unidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('porcentaje_envio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('costo_envio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('costo_con_envio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('porcentaje_utilidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('utilidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('venta_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_por_grupo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Suministro',
                'verbose_name_plural': 'Suministros',
                'db_table': 'cotizaciones_suministros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VistaAnalisis',
            fields=[
                ('id_vista', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('dimensions', models.JSONField()),
                ('metrica', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vista_analisis',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='vc_tab_categorias',
        ),
        migrations.DeleteModel(
            name='vc_tab_tgastos',
        ),
        migrations.DeleteModel(
            name='vc_tab_tgastos_d',
        ),
        migrations.DeleteModel(
            name='vc_tab_tipo',
        ),
        migrations.DeleteModel(
            name='cont_cias',
        ),
        migrations.DeleteModel(
            name='CotiMensajes',
        ),
        migrations.DeleteModel(
            name='CotiSeguimiento',
        ),
        migrations.DeleteModel(
            name='CotiServicios',
        ),
        migrations.DeleteModel(
            name='CotiSuministros',
        ),
        migrations.DeleteModel(
            name='DashboardOportunidad',
        ),
        migrations.DeleteModel(
            name='Representante',
        ),
        migrations.DeleteModel(
            name='vc_mov_cotizaciones',
        ),
        migrations.DeleteModel(
            name='vc_tab_ceyesa',
        ),
        migrations.DeleteModel(
            name='vc_tab_clientes',
        ),
        migrations.DeleteModel(
            name='vc_tab_estado',
        ),
        migrations.DeleteModel(
            name='vc_tab_hoffman',
        ),
        migrations.DeleteModel(
            name='vc_tab_rittal',
        ),
        migrations.DeleteModel(
            name='vc_tab_rockwell',
        ),
        migrations.DeleteModel(
            name='vc_tab_tproveedor',
        ),
        migrations.DeleteModel(
            name='VcTabBancos',
        ),
        migrations.AlterModelOptions(
            name='cotizacion',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='cotizacion',
            table='cotizaciones',
        ),
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
