# Generated by Django 5.2.4 on 2026-08-21 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SugerenciaQueja',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('anno', models.IntegerField(blank=True, null=True)),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('asunto', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, default='PENDIENTE', max_length=45, null=True)),
                ('anonimo', models.IntegerField(default=0)),
                ('tipo', models.CharField(default='S', max_length=1)),
                ('prioridad', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'sugerencias_quejas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SugerenciaAdjunto',
            fields=[
                ('id_adjunto', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to='buzon_adjuntos/')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('id_registro', models.ForeignKey(db_column='id_registro', on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='buzon_api.sugerenciaqueja')),
                ('subido_por', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sugerencias_adjuntos',
            },
        ),
        migrations.CreateModel(
            name='SugerenciaSeguimiento',
            fields=[
                ('id_seguimiento', models.AutoField(primary_key=True, serialize=False)),
                ('detalle', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_registro', models.ForeignKey(db_column='id_registro', on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='buzon_api.sugerenciaqueja')),
                ('usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sugerencias_seguimientos',
            },
        ),
    ]
