# Generated by Django 5.2.3 on 2025-11-05 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoEv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_proyecto', models.CharField(choices=[('infraestructura', 'Infraestructura'), ('tecnologia', 'Tecnología'), ('servicios', 'Servicios'), ('construccion', 'Construcción'), ('mineria', 'Minería'), ('automatizacion', 'Automatización Industrial'), ('otro', 'Otro')], default='infraestructura', max_length=50)),
                ('unidad_negocio', models.CharField(choices=[('Minería', 'Minería'), ('Petroquímica', 'Petroquímica'), ('Industria', 'Industria'), ('Safety', 'Safety')], default='Minería', max_length=100)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('modalidad_contratacion', models.CharField(choices=[('suma_alzada', 'Suma Alzada'), ('costo_reembolsable', 'Costo Reembolsable'), ('llave_en_mano', 'Llave en Mano'), ('mixto', 'Mixto')], default='suma_alzada', max_length=50)),
                ('entidad_cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('responsable', models.CharField(blank=True, max_length=255, null=True)),
                ('lider_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contacto_cliente_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('contacto_cliente_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contacto_cliente_telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_base_aprobada', models.DateField(blank=True, null=True)),
                ('etapa_actual', models.CharField(choices=[('inicio', 'Inicio'), ('planificacion', 'Planificación'), ('ejecucion', 'Ejecución'), ('monitoreo', 'Monitoreo y Control'), ('cierre', 'Cierre')], default='inicio', max_length=20)),
                ('estado', models.CharField(choices=[('Apertura', 'Apertura'), ('Inicio', 'Inicio'), ('Planificación', 'Planificación'), ('Ejecución', 'Ejecución'), ('Cierre', 'Cierre'), ('Cerrado', 'Cerrado'), ('Pausado', 'Pausado')], default='Apertura', max_length=20)),
                ('moneda', models.CharField(choices=[('USD', 'Dólar Estadounidense'), ('PEN', 'Sol Peruano')], default='USD', max_length=3)),
                ('presupuesto_gastos', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('presupuesto_hh', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('presupuesto_contingencia', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('presupuesto_utilidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('presupuesto_estimado', models.FloatField(default=0.0)),
                ('presupuesto_aprobado', models.FloatField(default=0.0)),
                ('gasto_real', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('costo_hh_real', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('gastos', models.TextField(blank=True, null=True)),
                ('hh', models.TextField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='MiembroEquipoEv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('rol', models.CharField(max_length=100)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='proyectos_ev.proyectoev')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialEv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('porcentaje_avance_fisico', models.FloatField(default=0.0)),
                ('porcentaje_tiempo_transcurrido', models.FloatField(default=0.0)),
                ('valor_ganado', models.FloatField(default=0.0)),
                ('valor_planificado', models.FloatField(default=0.0)),
                ('costo_real', models.FloatField(default=0.0)),
                ('desviacion_costo', models.FloatField(default=0.0)),
                ('desviacion_tiempo', models.FloatField(default=0.0)),
                ('spi', models.FloatField(default=0.0)),
                ('cpi', models.FloatField(default=0.0)),
                ('riesgos_abiertos', models.IntegerField(default=0)),
                ('severidad_media_riesgos', models.FloatField(default=0.0)),
                ('cantidad_reprogramaciones', models.IntegerField(default=0)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='proyectos_ev.proyectoev')),
            ],
        ),
        migrations.CreateModel(
            name='GastoReal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField()),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_reales', to='proyectos_ev.proyectoev')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('archivo', models.FileField(help_text='Archivo subido', upload_to='proyectos/%Y/%m/%d/')),
                ('tipo', models.CharField(choices=[('imagen', 'Imagen'), ('documento', 'Documento'), ('plano', 'Plano'), ('excel', 'Excel'), ('pdf', 'PDF'), ('otro', 'Otro')], default='documento', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('tamano_bytes', models.BigIntegerField(default=0)),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_subidos', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='proyectos_ev.proyectoev')),
            ],
            options={
                'verbose_name': 'Documento de Proyecto',
                'verbose_name_plural': 'Documentos de Proyectos',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='CronogramaVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la versión (ej: Cronograma v1, v2)', max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('es_activa', models.BooleanField(default=True, help_text='Versión activa del cronograma')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cronogramas_creados', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cronogramas', to='proyectos_ev.proyectoev')),
            ],
            options={
                'verbose_name': 'Versión de Cronograma',
                'verbose_name_plural': 'Versiones de Cronogramas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='AvanceFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances_fisicos', to='proyectos_ev.proyectoev')),
            ],
        ),
        migrations.CreateModel(
            name='AvanceFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto_acumulado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances_financieros', to='proyectos_ev.proyectoev')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(help_text='Número de ítem/tarea')),
                ('edt', models.CharField(blank=True, help_text='Código EDT/WBS (ej: 1.2.3)', max_length=50)),
                ('nivel', models.IntegerField(choices=[(1, 'Nivel 1'), (2, 'Nivel 2'), (3, 'Nivel 3'), (4, 'Nivel 4')], default=3, help_text='Nivel jerárquico (1-4)')),
                ('nombre', models.CharField(help_text='Nombre de la tarea', max_length=255)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada')),
                ('inicio', models.DateTimeField(blank=True, help_text='Fecha/hora de inicio (calculado)', null=True)),
                ('fin', models.DateTimeField(blank=True, help_text='Fecha/hora de fin (calculado)', null=True)),
                ('duracion_min', models.IntegerField(default=0, help_text='Duración en MINUTOS (no días)')),
                ('calendario', models.CharField(choices=[('8+1', '8+1 (Lun-Vie 8h+1h almuerzo, Sáb 4h)'), ('10', '10 horas/día continuo'), ('12', '12 horas/día continuo')], default='8+1', help_text='Tipo de calendario laboral', max_length=10)),
                ('es_hito', models.BooleanField(default=False, help_text='Es un hito (duración = 0)')),
                ('predecesoras', models.TextField(blank=True, help_text='Formato: 12,7:SS+1d,9:FF-8h (item:TIPO±lag)')),
                ('mostrar', models.BooleanField(default=True, help_text='Mostrar en Gantt')),
                ('timeline', models.BooleanField(default=False, help_text='Mostrar en Timeline')),
                ('es_resumen', models.BooleanField(default=False, help_text='Es tarea resumen (calculado según jerarquía)')),
                ('es_critica', models.BooleanField(default=False, help_text='Está en ruta crítica (holgura = 0)')),
                ('holgura_total', models.IntegerField(default=0, help_text='Holgura total en minutos')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('version', models.ForeignKey(help_text='Versión del cronograma a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='proyectos_ev.cronogramaversion')),
            ],
            options={
                'verbose_name': 'Tarea de Cronograma',
                'verbose_name_plural': 'Tareas de Cronograma',
                'ordering': ['item'],
            },
        ),
        migrations.CreateModel(
            name='TareaEv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('responsable', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('duracion', models.IntegerField(default=0)),
                ('peso', models.FloatField(default=0.0)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('finalizada', 'Finalizada'), ('atrasada', 'Atrasada')], default='pendiente', max_length=20)),
                ('avance_real', models.FloatField(default=0.0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='proyectos_ev.proyectoev')),
            ],
        ),
        migrations.CreateModel(
            name='HorasHombreReal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horas', models.DecimalField(decimal_places=2, max_digits=6)),
                ('recurso', models.CharField(blank=True, max_length=100, null=True)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horas_reales', to='proyectos_ev.tareaev')),
            ],
        ),
        migrations.CreateModel(
            name='CurvaEv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('pv', models.FloatField(default=0.0)),
                ('ev', models.FloatField(default=0.0)),
                ('ac', models.FloatField(default=0.0)),
                ('fuente', models.CharField(default='calculado', max_length=100)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curva_s', to='proyectos_ev.proyectoev')),
            ],
            options={
                'unique_together': {('proyecto', 'fecha')},
            },
        ),
        migrations.AddIndex(
            model_name='cronogramaversion',
            index=models.Index(fields=['proyecto', '-fecha_creacion'], name='proyectos_e_proyect_acbb30_idx'),
        ),
        migrations.AddIndex(
            model_name='tarea',
            index=models.Index(fields=['version', 'item'], name='proyectos_e_version_281e43_idx'),
        ),
        migrations.AddIndex(
            model_name='tarea',
            index=models.Index(fields=['version', 'es_critica'], name='proyectos_e_version_90800a_idx'),
        ),
        migrations.AddIndex(
            model_name='tarea',
            index=models.Index(fields=['version', 'nivel'], name='proyectos_e_version_1beec1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tarea',
            unique_together={('version', 'item')},
        ),
    ]
