# Generated by Django 5.2.3 on 2025-11-07 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_ev', '0002_checklistcalidad_comunicacion_itemchecklist_nota_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeEjecutivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('resumen_ejecutivo', 'Resumen Ejecutivo'), ('avance_mensual', 'Informe de Avance Mensual'), ('riesgos', 'Informe de Riesgos'), ('costos_evm', 'Informe de Costos EVM'), ('cronograma', 'Informe de Cronograma'), ('general', 'Informe General del Proyecto')], max_length=30)),
                ('formato', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel')], max_length=10)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='informes/%Y/%m/')),
                ('estado', models.CharField(choices=[('generando', 'Generando'), ('completado', 'Completado'), ('error', 'Error')], default='generando', max_length=20)),
                ('mensaje_error', models.TextField(blank=True)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_desde', models.DateField(blank=True, help_text='Fecha inicio del período del informe', null=True)),
                ('fecha_hasta', models.DateField(blank=True, help_text='Fecha fin del período del informe', null=True)),
                ('configuracion', models.JSONField(blank=True, default=dict, help_text='Configuración adicional del informe (secciones a incluir, filtros, etc.)')),
                ('generado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_generados', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes', to='proyectos_ev.proyectoev')),
            ],
            options={
                'verbose_name': 'Informe Ejecutivo',
                'verbose_name_plural': 'Informes Ejecutivos',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
