# Generated by Django 5.2.3 on 2025-11-08 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_ev', '0003_informeejecutivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternativaProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la alternativa de proyecto', max_length=255)),
                ('codigo', models.CharField(help_text='Código único de la alternativa', max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de la alternativa', null=True)),
                ('inversion_inicial', models.DecimalField(decimal_places=2, help_text='Inversión inicial requerida (en USD o moneda local)', max_digits=15)),
                ('flujos_futuros', models.JSONField(default=list, help_text='Lista de flujos de efectivo futuros por período (ej: [10000, 15000, 20000])')),
                ('tasa_retorno_esperada', models.DecimalField(decimal_places=2, default=0.0, help_text='Tasa de retorno esperada (ej: 0.15 = 15%)', max_digits=5)),
                ('vpn', models.DecimalField(blank=True, decimal_places=2, help_text='Valor Presente Neto calculado', max_digits=15, null=True)),
                ('tir', models.DecimalField(blank=True, decimal_places=2, help_text='Tasa Interna de Retorno calculada', max_digits=5, null=True)),
                ('roi', models.DecimalField(blank=True, decimal_places=2, help_text='Return on Investment calculado', max_digits=5, null=True)),
                ('payback', models.DecimalField(blank=True, decimal_places=2, help_text='Período de recuperación en años', max_digits=5, null=True)),
                ('relacion_beneficio_costo', models.DecimalField(blank=True, decimal_places=2, help_text='Relación Beneficio/Costo', max_digits=5, null=True)),
                ('impacto_estrategico', models.IntegerField(default=5, help_text='Impacto estratégico (1=bajo, 10=alto)')),
                ('urgencia', models.IntegerField(default=5, help_text='Urgencia de implementación (1=baja, 10=alta)')),
                ('nivel_riesgo', models.IntegerField(default=5, help_text='Nivel de riesgo (1=muy bajo, 10=muy alto)')),
                ('complejidad_tecnica', models.IntegerField(default=5, help_text='Complejidad técnica (1=simple, 10=muy compleja)')),
                ('alineamiento_estrategico', models.IntegerField(default=5, help_text='Alineamiento con estrategia organizacional (1=bajo, 10=alto)')),
                ('ventajas', models.JSONField(blank=True, default=list, help_text='Lista de ventajas de la alternativa')),
                ('desventajas', models.JSONField(blank=True, default=list, help_text='Lista de desventajas de la alternativa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas_proyecto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alternativa de Proyecto',
                'verbose_name_plural': 'Alternativas de Proyecto',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='EscenarioEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Nombre descriptivo del escenario (ej: 'Escenario Conservador', 'Escenario Optimista')", max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del escenario y sus condiciones', null=True)),
                ('peso_roi', models.DecimalField(decimal_places=2, default=0.25, help_text='Peso para ROI (Return on Investment) - Retorno de inversión', max_digits=5)),
                ('peso_vpn', models.DecimalField(decimal_places=2, default=0.25, help_text='Peso para VPN (Valor Presente Neto)', max_digits=5)),
                ('peso_impacto', models.DecimalField(decimal_places=2, default=0.2, help_text='Peso para impacto estratégico del proyecto', max_digits=5)),
                ('peso_urgencia', models.DecimalField(decimal_places=2, default=0.15, help_text='Peso para urgencia de implementación', max_digits=5)),
                ('peso_riesgo', models.DecimalField(decimal_places=2, default=0.15, help_text='Peso para nivel de riesgo (menor riesgo es mejor)', max_digits=5)),
                ('tasa_descuento', models.DecimalField(decimal_places=2, default=0.1, help_text='Tasa de descuento para cálculos financieros (ej: 0.10 = 10%)', max_digits=5)),
                ('tolerancia_costo', models.IntegerField(default=5, help_text='Tolerancia al costo (escala 1-10, donde 10 es alta tolerancia)')),
                ('incertidumbre', models.DecimalField(decimal_places=2, default=0.15, help_text='Nivel de incertidumbre para simulaciones Monte Carlo (ej: 0.15 = 15%)', max_digits=5)),
                ('usar_ia_generativa', models.BooleanField(default=True, help_text='Usar IA generativa (Gemini) para análisis cualitativo')),
                ('usar_random_forest', models.BooleanField(default=True, help_text='Usar Random Forest para predicción')),
                ('usar_monte_carlo', models.BooleanField(default=True, help_text='Usar simulación Monte Carlo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('es_predeterminado', models.BooleanField(default=False, help_text='Marcar como escenario predeterminado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escenarios_evaluacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Escenario de Evaluación',
                'verbose_name_plural': 'Escenarios de Evaluación',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionEstrategica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la evaluación estratégica', max_length=255)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción y objetivo de la evaluación', null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='borrador', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_evaluacion', models.DateTimeField(blank=True, help_text='Fecha en que se ejecutó la evaluación', null=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, help_text='Fecha de aprobación/rechazo', null=True)),
                ('puntaje_mejor_alternativa', models.DecimalField(blank=True, decimal_places=3, help_text='Puntaje de la mejor alternativa', max_digits=5, null=True)),
                ('conclusion_ia', models.TextField(blank=True, help_text='Conclusión generada por IA generativa', null=True)),
                ('recomendaciones_ia', models.JSONField(blank=True, default=list, help_text='Lista de recomendaciones generadas por IA')),
                ('metodos_aplicados', models.JSONField(default=list, help_text="Lista de métodos aplicados (ej: ['Monte Carlo', 'IA Generativa', 'Ponderado'])")),
                ('alternativa_recomendada', models.ForeignKey(blank=True, help_text='Alternativa con mejor puntaje global', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recomendada_en', to='proyectos_ev.alternativaproyecto')),
                ('alternativas', models.ManyToManyField(help_text='Alternativas evaluadas', related_name='evaluaciones', to='proyectos_ev.alternativaproyecto')),
                ('aprobador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('escenario', models.ForeignKey(help_text='Escenario utilizado para la evaluación', on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones', to='proyectos_ev.escenarioevaluacion')),
                ('proyecto_asociado', models.ForeignKey(blank=True, help_text='Proyecto al que pertenece esta evaluación (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_estrategicas', to='proyectos_ev.proyectoev')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_estrategicas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evaluación Estratégica',
                'verbose_name_plural': 'Evaluaciones Estratégicas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoMetodoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('vpn', 'Valor Presente Neto'), ('tir', 'Tasa Interna de Retorno'), ('roi', 'Return on Investment'), ('payback', 'Período de Recuperación'), ('bc', 'Relación Beneficio/Costo'), ('ponderado', 'Evaluación Ponderada'), ('monte_carlo', 'Simulación Monte Carlo'), ('random_forest', 'IA Random Forest'), ('ia_generativa', 'IA Generativa (Gemini)'), ('reglas', 'Reglas de Negocio')], help_text='Método de evaluación aplicado', max_length=30)),
                ('puntaje', models.DecimalField(decimal_places=3, help_text='Puntaje obtenido (puede ser VPN, score normalizado, etc.)', max_digits=15)),
                ('puntaje_normalizado', models.DecimalField(blank=True, decimal_places=3, help_text='Puntaje normalizado entre 0 y 1 para comparación', max_digits=5, null=True)),
                ('comentario', models.TextField(blank=True, help_text='Comentario o explicación del resultado', null=True)),
                ('explicacion_simple', models.TextField(blank=True, help_text='Explicación en lenguaje simple para no-PMPs', null=True)),
                ('estadisticas_adicionales', models.JSONField(blank=True, default=dict, help_text='Estadísticas extra (media, desv std, percentiles, etc.)')),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('alternativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_evaluacion', to='proyectos_ev.alternativaproyecto')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='proyectos_ev.evaluacionestrategica')),
            ],
            options={
                'verbose_name': 'Resultado de Método de Evaluación',
                'verbose_name_plural': 'Resultados de Métodos de Evaluación',
                'ordering': ['-puntaje_normalizado'],
                'unique_together': {('evaluacion', 'alternativa', 'metodo')},
            },
        ),
    ]
