# Generated by Django 5.2.3 on 2025-11-13 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_ev', '0004_alternativaproyecto_escenarioevaluacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareaev',
            name='area',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='tareaev',
            name='rol',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='tareaev',
            name='tipo_responsable',
            field=models.CharField(choices=[('persona', 'Persona / Colaborador'), ('area', 'Area / Unidad'), ('proveedor', 'Proveedor externo')], default='persona', max_length=20),
        ),
    ]
